deploy:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.92.2'
        extended: true

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0'

    - run: npm ci
    - run: npm run start
    - run: hugo --gc --minify